spring:
    security:
        oauth2:
            client:
                registration:
                    github:
                        clientId: 5cce5eab6fdd67434c35 #ran out of time to add secret in aws i know this is a security risk kindly excuse will add it to the aws -> ubuntu image in future as env var
                        clientSecret: 002de6b6da974abf8079316f163bc6640bb3ea0f
    sql:
        init:
            mode: always


    datasource:
        url: jdbc:mysql://127.0.0.1:3306/bookdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: bookuser
        password: password
    jpa:
        database: mysql
        hibernate.ddl-auto: validate
        generate-ddl: true
        show-sql: true
        properties:
            hibernate:
                show-sql: true
                format_sql: true


    liquibase:
        change-log: db/changelog/changelog-master.xml
        user: bookadmin
        password: password

logging:
    level:
        org:
            hibernate:
                type:
                    descriptor:
                        sql: trace

